version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: myreviews-db
    environment:
      POSTGRES_DB: myreviews
      POSTGRES_USER: myreviews_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myreviews_user -d myreviews"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./server
    container_name: myreviews-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: myreviews
      DB_USER: myreviews_user
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
      PORT: 3000
      NODE_ENV: production
      CORS_ORIGIN: "*"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: